version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing AWS CDK
      - npm install aws-cdk -g
      - echo Installing Dotnet 6
      - /usr/local/bin/dotnet-install.sh --channel LTS
      - cdk --version
  build:
    commands:
      - echo Build started on `date`
#      - cd Core.Authentication
      - cd $CODEBUILD_SRC_DIR/Core.Gaming/src/Core.Gaming.API
      - ls
      - cd $CODEBUILD_SRC_DIR/Core.Gaming
      - cdk deploy

  post_build:
    commands:
      - echo Build completed on `date`
