permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0"]

    steps:
      - uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::844587791486:role/GithubActionRole
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-west-1 # use your region here.
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
          dotnet-quality: "preview"

      - name: Building Gaming API
        run: |
          cd ./Core.Gaming/src/Core.Gaming.API
          dotnet restore
          dotnet build -c Pipeline --no-restore

      - name: Run Gaming API
        run: |
          cd ./Core.Gaming/src/Core.Gaming.API
          chmod +x ./run.sh
          ./run.sh &
        shell: bash

      - name: Test API
        run: |
          cd ./Core.Gaming
          dotnet test --no-restore --verbosity normal
