name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
          dotnet-quality: "preview"

      - name: Enter Gaming Directory
        run: ls

      - name: Enter Gaming Directory
        run: |
          cd ./Core.Gaming/src/Core.Gaming.API
          dotnet restore
          dotnet build -c Pipeline --no-restore

      - name: Test
        run: |
          cd ../..
          dotnet test --no-restore --verbosity normal
